### ISSUE TITLE
Создать список вопросов.

### ISSUE THREAD

**Issue by levonikitatech** [levonikitatech/fail-avoidance#3]
Сделать в коде массив Question представляющий следующую таблицу ответов.

1. | смелый | бдительный | предприимчивый
2. | кроткий | робкий | упрямый
3. | осторожный | решительный | пессимистичный
4. | непостоянный | бесцеремонный | внимательный
5. | неумный | трусливый | недумающий
6. | ловкий | бойкий | удалой
7. | хладнокровный | колеблющийся | удалой
8. | стремительный | легкомысленный | боязливый
9. | незадумывающийся | жеманный | непредусмотрительный
10. | оптимистичный | добросовестный | чуткий
11. | меланхоличный | сомневающийся | неустойчивый
12. | трусливый | небрежный | взволнованный
13. | опрометчивый | тихий | боязливый
14. | внимательный | неблагоразумный | смелый
15. | рассудительный | быстрый | мужественный
16. | предприимчивый | осторожный | предусмотрительный
17. | взволнованный | рассеянный | робкий
18. | малодушный | неосторожный | бесцеремонный
19. | пугливый | нерешительный | нервный
20. | исполнительный | преданный | нервный
21. | предусмотрительный | бойкий | отчаянный
22. | укрощенный | безразличный | небрежный
23. | осторожный | беззаботный | терпеливый
24. | разумный | заботливый | храбрый
25. | предвидящий | неустрашимый | добросовестный
26. | поспешный | пугливый | беззаботный
27. | рассеянный | опрометчивый | пессимистичный
28. | осмотрительный | рассудительный | предприимчивый
29. | тихий | неорганизованный | боязливый
30. | оптимистичный | бдительный | беззаботный

**Comment by levonikitatech** [comment]
@alex19EP Если ещё не начал делай в questions.hpp

**Comment by alex19EP** [comment]
@levonikitatech  ты только что отправил пинг какому то программисту на тайпскрипт. отлично! нам нужны новые контрибутеры. а то я устал уже. слишком большой техдолг на мне.

**Comment by levonikitatech** [comment]
@alex19EP Забыл упомянуть. Новая рабочая ветка Pascalheaders
